resources:
  repositories:
    - repository: pipeline-templates
      type: github
      name: lsportsltd/devops-pipeline-templates
      endpoint: lsportsltd

trigger: none

stages:
  - template: general/generic-package-CICD.yaml@pipeline-templates
    parameters:
      packageManager: 'maven'
      language: 'java'
      languageVersion: '17'
      artifactImageLocation: '/app/target'
      locationToBuild: 'trade360-java-sdk/sdk/trade360-java-sdk'
      serviceName: sdk
      
  - template: general/generic-package-CICD.yaml@pipeline-templates
    parameters:
      packageManager: 'maven'
      language: 'java'
      languageVersion: '17'
      artifactImageLocation: '/app/samples/trade360-samples/target'
      locationToBuild: 'trade360-java-sdk/samples/trade360-samples'
      dockerfilePath: 'trade360-java-sdk'
      serviceName: samples

  - stage: PublishToMavenCentral
    displayName: 'Publish to Maven Central'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: PublishArtifacts
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DownloadSecureFile@1
            name: mavenSettings
            inputs:
              secureFile: 'settings.xml'

          - task: Maven@3
            inputs:
              mavenPomFile: 'trade360-java-sdk/sdk/trade360-java-sdk/pom.xml'
              goals: 'clean deploy'
              options: '-P release -s $(mavenSettings.secureFilePath)'
              publishJUnitResults: false
            env:
              MAVEN_USERNAME: $(devopsr.maven.username)
              MAVEN_PASSWORD: $(devopsr.maven.password)
              MAVEN_TOKEN: $(devopsr.maven.token)
              MAVEN_AUTH: $(devopsr.maven.auth)
              MAVEN_NAMESPACE: $(devopsr.maven.namespace)

      
      
