resources:
  repositories:
    - repository: pipeline-templates
      type: github
      name: lsportsltd/devops-pipeline-templates
      endpoint: lsportsltd
      ref: feature/PLT-123-shirb-uff

pr: none
trigger:
  branches:
    include:
     - main
  paths:
    include:
    - sdk/
    
stages:
  - template: general/generic-package-CICD.yaml@pipeline-templates
    parameters:
      packageManager: 'maven'
      language: 'java'
      languageVersion: '17'
      artifactImageLocation: '/app/target'
      locationToBuild: 'trade360-java-sdk/sdk/trade360-java-sdk'
      serviceName: 'trade360_java_sdk'
      group: trd
      domain: trade360-sdk
      product: stm
      team: guns-n-roses
      
  - stage: PublishToMavenCentral
    displayName: 'Publish to Maven Central'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
    - deployment: PublishToMavenCentral
      environment: prod
      displayName: 'Publish to Maven Central'
      timeoutInMinutes: "120"
      pool: k8s-agents-ci
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
                fetchDepth: 0
                
              - task: DownloadSecureFile@1
                name: mavenSettings
                inputs:
                  secureFile: 'settings.xml'

              - task: DownloadSecureFile@1
                name: gpgKeys
                inputs:
                  secureFile: 'gpg-keys.txt'

              - task: CopyFiles@2
                inputs:
                  sourceFiles: '$(mavenSettings.secureFilePath)'
                  targetFolder: '$(Build.SourcesDirectory)/trade360-java-sdk'

              # Read GPG keys from secure file
              - script: |
                  # Source the GPG keys file to get the variables
                  source "$(gpgKeys.secureFilePath)"
                  # Export them as pipeline variables
                  echo "##vso[task.setvariable variable=GPG_PASSPHRASE]$GPG_PASSPHRASE"
                  echo "##vso[task.setvariable variable=GPG_PRIVATE_KEY]$PRIVATE_KEY"
                displayName: 'Set GPG Variables'

              - script: |
                  mavenUsername=$(aws ssm get-parameter --with-decryption --name /devopsr/maven/token/username | jq -r .Parameter.Value)
                  mavenPassword=$(aws ssm get-parameter --with-decryption --name /devopsr/maven/token/password | jq -r .Parameter.Value)

                  echo "##vso[task.setvariable variable=MAVEN_USERNAME]$mavenUsername"
                  echo "##vso[task.setvariable variable=MAVEN_PASSWORD]$mavenPassword"
                displayName: 'Set Maven Secret Variables'

              - task: Docker@2
                displayName: 'Build Docker Image'
                inputs:
                  command: 'build'
                  dockerfile: '$(Build.SourcesDirectory)/sdk/trade360-java-sdk/Dockerfile.publish'
                  buildContext: '$(Build.SourcesDirectory)/trade360-java-sdk'
                  tags: 'maven-publisher:latest'
                  arguments: '--progress=plain --no-cache --build-arg=$(Build.SourceVersion) --build-arg MAVEN_USERNAME=$(MAVEN_USERNAME) --build-arg MAVEN_PASSWORD=$(MAVEN_PASSWORD) --build-arg GPG_PRIVATE_KEY="$(GPG_PRIVATE_KEY)" --build-arg GPG_PASSPHRASE="$(GPG_PASSPHRASE)"'
        
