resources:
  repositories:
    - repository: pipeline-templates
      type: github
      name: lsportsltd/devops-pipeline-templates
      endpoint: lsportsltd
      ref: yehorazl-patch-2

trigger: none

stages:
  - template: general/generic-package-CICD.yaml@pipeline-templates
    parameters:
      packageManager: 'maven'
      language: 'java'
      languageVersion: '17'
      artifactImageLocation: '/app/sdk/trade360-java-sdk/target'
      locationToBuild: 'trade360-java-sdk/sdk/trade360-java-sdk'
      dockerfilePath: 'trade360-java-sdk'
